$tag = git describe --always --tags "--abbrev=0"
$revision = git describe --always --tags

# Convert git tag/hash to proper version format for AssemblyVersion
# AssemblyVersion requires format: major.minor.build.revision
if ($tag -match "^v?(\d+)\.(\d+)\.(\d+)") {
    # If we have a proper semantic version tag, use it
    $assemblyVersion = $tag -replace "^v", ""
    # Ensure we have 4 components (add .0 if only 3 components)
    if ($assemblyVersion -notmatch "^\d+\.\d+\.\d+\.\d+$") {
        $assemblyVersion += ".0"
    }
} else {
    # If no proper tag exists, use a default version
    $assemblyVersion = "1.0.0.0"
}

$text = @"
// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("$assemblyVersion")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File (Join-Path (Split-Path $PSScriptRoot -Parent) "GitVersion.cs") -Encoding utf8


$xml = [xml](Get-Content (Join-Path (Split-Path $PSScriptRoot -Parent) "QuickLook.Plugin.Metadata.Base.config"))
$xml.Metadata.Version="$revision"
$xml.Save((Join-Path (Split-Path $PSScriptRoot -Parent) "QuickLook.Plugin.Metadata.config"))