name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: QuickLook.Plugin.SqliteViewer.sln
  
  # Configuration type to build.
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch full history for GitVersion
        fetch-depth: 0
        submodules: true

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Update version
      shell: powershell
      run: |
        Set-Location Scripts
        .\update-version.ps1

    - name: Build solution
      run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform="Any CPU" ${{ env.SOLUTION_FILE_PATH }}

    - name: Create plugin package
      shell: powershell
      run: |
        Set-Location Scripts
        .\pack-zip.ps1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QuickLook.Plugin.SqliteViewer-${{ github.sha }}
        path: QuickLook.Plugin.SqliteViewer.qlplugin
        retention-days: 30

    - name: Upload release binaries
      uses: actions/upload-artifact@v4
      with:
        name: Release-Binaries-${{ github.sha }}
        path: bin/Release/
        retention-days: 30

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: QuickLook.Plugin.SqliteViewer-${{ github.sha }}

    - name: Get tag name
      id: tag_name
      shell: bash
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
        name: QuickLook SQLite Viewer ${{ steps.tag_name.outputs.TAG_NAME }}
        draft: false
        prerelease: ${{ contains(steps.tag_name.outputs.TAG_NAME, '-') }}
        files: QuickLook.Plugin.SqliteViewer.qlplugin
        body: |
          ## Changes in this Release
          
          ### Features
          - Enhanced SQLite database viewing with tabbed interface
          - Sidebar navigation for quick table access
          - Performance optimizations for large databases
          - Modern UI with dark theme support
          
          ### Installation
          1. Download the `QuickLook.Plugin.SqliteViewer.qlplugin` file below
          2. Copy it to your QuickLook plugins directory
          3. Restart QuickLook
          
          ### System Requirements
          - Windows 10/11
          - .NET Framework 4.6.2 or higher
          - QuickLook 3.7 or higher